name: Update latest blog posts
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse RSS for blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://mijolabs.remotenode.io/posts/index.xml"
          max_post_count: 3
          template: "$newline - $randomEmoji(💯,🔥,💫,🚀,🌮) **[$title]($url)**  $newline*$description*$newline"
          commit_message: "Update latest blog posts"
          enable_keepalive: false
          committer_username: mijolabs-bot
          committer_email: mijolabs-bot@remotenode.io
